<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ReadModelService.Worker-4416e0da-7d80-4aa7-9137-c3468f697dd9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.2.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EventBus\EventBus.Abstractions\EventBus.Abstractions.csproj" />
    <ProjectReference Include="..\ReadModelService.Application\ReadModelService.Application.csproj" />
    <ProjectReference Include="..\ReadModelService.DI\ReadModelService.DI.csproj" />
  </ItemGroup>
</Project>
