<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-BorrowingPowerService.Worker-d78a93d7-061f-470c-a16d-d3d9d8d70c1a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EventBus\EventBus.Abstractions\EventBus.Abstractions.csproj" />
    <ProjectReference Include="..\BorrowingPowerService.Application\BorrowingPowerService.Application.csproj" />
    <ProjectReference Include="..\BorrowingPowerService.DI\BorrowingPowerService.DI.csproj" />
  </ItemGroup>
</Project>
